-- PostgreSQL CDSS schema and seed data. Run against the target database.

CREATE TABLE IF NOT EXISTS clinical_rules (
id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_code                 VARCHAR(50)     NOT NULL,
    rule_name                 VARCHAR(200)    NOT NULL,
    description               TEXT            NULL,
    domain                    VARCHAR(40) NOT NULL DEFAULT 'vital_sign'
        CHECK (domain IN ('vital_sign', 'lab_result', 'medication', 'allergy_interaction', 'drug_lab_interaction', 'drug_drug_interaction', 'composite')),
    severity                  VARCHAR(40) NOT NULL DEFAULT 'warning'
        CHECK (severity IN ('critical', 'warning', 'info')),
    severity_tier             SMALLINT NOT NULL DEFAULT 2,
    is_active                 SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    suppression_window_hrs    BIGINT    NOT NULL DEFAULT 24,
    cooldown_hrs              BIGINT    NOT NULL DEFAULT 0,
    requires_acknowledgment   SMALLINT NOT NULL DEFAULT 0 CHECK (requires_acknowledgment IN (0, 1)),
    fhir_detected_issue_meta  JSON            NULL,
    
    
    
    
    
    
    
    
    created_at                TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_rule_code UNIQUE (rule_code)
);
CREATE INDEX IF NOT EXISTS idx_domain_active ON clinical_rules (domain, is_active);
CREATE INDEX IF NOT EXISTS idx_severity_active ON clinical_rules (severity, is_active);
CREATE TABLE IF NOT EXISTS rule_criteria (
id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_id               BIGINT    NOT NULL,
    data_domain           VARCHAR(40) NOT NULL
        CHECK (data_domain IN ('vital', 'lab', 'medication', 'allergy', 'demographic')),
    parameter_key         VARCHAR(100)    NOT NULL,
    operator              VARCHAR(40) NOT NULL
        CHECK (operator IN ('gt', 'gte', 'lt', 'lte', 'eq', 'neq', 'contains', 'not_contains', 'in_set', 'between')),
    threshold_value       DECIMAL(12, 4)  NULL,
    threshold_value2      DECIMAL(12, 4)  NULL,
    threshold_unit        VARCHAR(30)     NULL,
    string_match_pattern  VARCHAR(500)    NULL,
    logic_join            VARCHAR(40) NOT NULL DEFAULT 'AND' CHECK (logic_join IN ('AND', 'OR')),
    sort_order            SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uq_rule_criteria UNIQUE (rule_id, parameter_key, sort_order),
    CONSTRAINT fk_rc_rule FOREIGN KEY (rule_id) REFERENCES clinical_rules (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_rule_id ON rule_criteria (rule_id);
CREATE TABLE IF NOT EXISTS patient_observations (
id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id                VARCHAR(20)         NOT NULL,
    observation_type          VARCHAR(40) NOT NULL
        CHECK (observation_type IN ('vital_sign', 'lab_result', 'medication_active', 'allergy_flag', 'clinical_note')),
    loinc_code                VARCHAR(20)         NULL,
    parameter_key             VARCHAR(100)        NOT NULL,
    numeric_value             DECIMAL(12, 4)      NULL,
    string_value              VARCHAR(500)        NULL,
    unit                      VARCHAR(30)         NULL,
    reference_range_low       DECIMAL(12, 4)      NULL,
    reference_range_high      DECIMAL(12, 4)      NULL,
    status                    VARCHAR(40) NOT NULL DEFAULT 'final'
        CHECK (status IN ('final', 'preliminary', 'entered-in-error', 'amended')),
    recorded_by               VARCHAR(100)        NULL,
    fhir_observation_payload  JSON                NULL,
    
    
    
    
    
    
    
    
    recorded_at               TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_patient_param ON patient_observations (patient_id, parameter_key);
CREATE INDEX IF NOT EXISTS idx_patient_type ON patient_observations (patient_id, observation_type);
CREATE INDEX IF NOT EXISTS idx_recorded_at ON patient_observations (recorded_at);
CREATE TABLE IF NOT EXISTS patient_alert_states (
id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id                    VARCHAR(20)     NOT NULL,
    rule_id                       BIGINT    NOT NULL,
    triggering_observation_id     BIGINT    NULL,
    state                         VARCHAR(40) NOT NULL DEFAULT 'active'
        CHECK (state IN ('active', 'resolved', 'overridden', 'suppressed', 'expired')),
    severity_tier                 SMALLINT NOT NULL DEFAULT 2,
    matched_criteria_snapshot     JSON            NULL,
    fhir_detected_issue_payload   JSON            NULL,
    
    
    
    
    
    
    
    
    
    triggered_at                  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at                   TIMESTAMP       NULL,
    expires_at                    TIMESTAMP       NULL,
    PRIMARY KEY (id),

    CONSTRAINT fk_pas_rule FOREIGN KEY (rule_id) REFERENCES clinical_rules (id),
    CONSTRAINT fk_pas_obs  FOREIGN KEY (triggering_observation_id) REFERENCES patient_observations (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_patient_state ON patient_alert_states (patient_id, state);
CREATE INDEX IF NOT EXISTS idx_patient_rule ON patient_alert_states (patient_id, rule_id);
CREATE INDEX IF NOT EXISTS idx_expires ON patient_alert_states (expires_at);
CREATE INDEX IF NOT EXISTS idx_severity_state ON patient_alert_states (severity_tier, state);
CREATE TABLE IF NOT EXISTS alert_overrides (
id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alert_state_id            BIGINT    NOT NULL,
    clinician_user_id         VARCHAR(50)     NOT NULL,
    clinician_role            VARCHAR(80)     NULL,
    override_action           VARCHAR(40) NOT NULL
        CHECK (override_action IN ('dismissed', 'acknowledged', 'escalated', 'patient_informed', 'order_cancelled')),
    clinical_justification    TEXT            NOT NULL,
    icd10_reason_code         VARCHAR(20)     NULL,
    patient_informed          SMALLINT NOT NULL DEFAULT 0 CHECK (patient_informed IN (0, 1)),
    patient_informed_by       VARCHAR(100)    NULL,
    clinician_ip              VARCHAR(45)     NULL,
    session_token_hash        VARCHAR(255)    NULL,
    overridden_at             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),

    CONSTRAINT fk_ao_alert FOREIGN KEY (alert_state_id) REFERENCES patient_alert_states (id)
);
CREATE INDEX IF NOT EXISTS idx_alert_state ON alert_overrides (alert_state_id);
CREATE INDEX IF NOT EXISTS idx_clinician ON alert_overrides (clinician_user_id);
CREATE INDEX IF NOT EXISTS idx_overridden_at ON alert_overrides (overridden_at);
INSERT INTO clinical_rules
    (rule_code, rule_name, domain, severity, severity_tier, suppression_window_hrs, cooldown_hrs, requires_acknowledgment)
VALUES
    ('HYPER-K-001',         'Hyperkalemia — Critical',                  'lab_result',           'critical', 1, 48, 12, 1),
    ('HYPER-K-DIGOXIN-001', 'Hyperkalemia with Active Digoxin',         'drug_lab_interaction',  'critical', 1, 48, 12, 1),
    ('HYPERTENSION-001',    'Hypertensive Crisis — BP > 180/120',        'vital_sign',           'critical', 1, 12,  4, 1),
    ('NSAID-ACE-001',       'NSAID + ACE Inhibitor Interaction',         'drug_drug_interaction', 'warning',  2, 72, 24, 1),
    ('PENICILLIN-ALLERGY',  'Penicillin Allergy — Active Prescription',  'allergy_interaction',  'critical', 1,  0,  0, 1),
    ('OVERDUE-LAB-001',     'Overdue Lab Follow-up > 7 Days',            'lab_result',           'info',     3, 24, 24, 0)
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id, data_domain, parameter_key, operator, threshold_value, threshold_unit, logic_join, sort_order)
SELECT id, 'lab', 'serum_potassium', 'gt', 5.5, 'mEq/L', 'AND', 1 FROM clinical_rules WHERE rule_code = 'HYPER-K-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id, data_domain, parameter_key, operator, threshold_value, threshold_unit, logic_join, sort_order)
SELECT id, 'lab', 'serum_potassium', 'gt', 5.0, 'mEq/L', 'AND', 1 FROM clinical_rules WHERE rule_code = 'HYPER-K-DIGOXIN-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id, data_domain, parameter_key, operator, string_match_pattern, logic_join, sort_order)
SELECT id, 'medication', 'medication_name', 'contains', 'digoxin', 'AND', 2 FROM clinical_rules WHERE rule_code = 'HYPER-K-DIGOXIN-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id, data_domain, parameter_key, operator, threshold_value, threshold_unit, logic_join, sort_order)
SELECT id, 'vital', 'systolic_bp', 'gt', 180, 'mmHg', 'OR', 1 FROM clinical_rules WHERE rule_code = 'HYPERTENSION-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id, data_domain, parameter_key, operator, threshold_value, threshold_unit, logic_join, sort_order)
SELECT id, 'vital', 'diastolic_bp', 'gt', 120, 'mmHg', 'AND', 2 FROM clinical_rules WHERE rule_code = 'HYPERTENSION-001'
ON CONFLICT DO NOTHING;
INSERT INTO clinical_rules
    (rule_code, rule_name, domain, severity, severity_tier,
     suppression_window_hrs, cooldown_hrs, requires_acknowledgment, description)
VALUES
    ('TACHYCARDIA-001',       'Critical Tachycardia',              'vital_sign',  'critical', 1, 12,  4, 1, 'Heart rate > 150 bpm — evaluate for arrhythmia or haemodynamic instability.'),
    ('BRADYCARDIA-001',       'Critical Bradycardia',              'vital_sign',  'critical', 1, 12,  4, 1, 'Heart rate < 40 bpm — risk of haemodynamic compromise.'),
    ('HYPOXIA-001',           'Critical Hypoxia',                  'vital_sign',  'critical', 1, 12,  4, 1, 'SpO₂ < 90% — supplemental O₂ urgently required.'),
    ('HYPERTHERMIA-001',      'Hyperthermia / Fever',              'vital_sign',  'warning',  2, 24,  8, 0, 'Temperature > 38.5 °C — evaluate for infection or sepsis.'),
    ('HYPOTHERMIA-001',       'Hypothermia',                       'vital_sign',  'warning',  2, 24,  8, 0, 'Temperature < 35 °C — active warming and monitoring required.'),
    ('GLUCOSE-CRITICAL-LOW',  'Severe Hypoglycaemia',              'lab_result',  'critical', 1, 24, 12, 1, 'Glucose < 54 mg/dL — administer glucose immediately.'),
    ('GLUCOSE-LOW-001',       'Hypoglycaemia',                     'lab_result',  'warning',  2, 24,  8, 1, 'Glucose < 70 mg/dL — monitor closely and consider carbohydrate supplementation.'),
    ('GLUCOSE-HIGH-001',      'Hyperglycaemia',                    'lab_result',  'warning',  2, 24,  8, 0, 'Glucose > 200 mg/dL — review diabetic management plan.'),
    ('GLUCOSE-CRITICAL-HIGH', 'Critical Hyperglycaemia',           'lab_result',  'critical', 1, 24, 12, 1, 'Glucose > 500 mg/dL — risk of DKA. Urgent review required.'),
    ('HGB-CRITICAL-LOW',      'Critical Anaemia',                  'lab_result',  'critical', 1, 24, 12, 1, 'Haemoglobin < 7 g/dL — consider urgent transfusion.'),
    ('HGB-LOW-001',           'Anaemia',                           'lab_result',  'warning',  2, 24,  8, 0, 'Haemoglobin < 12 g/dL — evaluate for cause of anaemia.'),
    ('CHOL-HIGH-001',         'High Total Cholesterol',            'lab_result',  'warning',  2, 48, 24, 0, 'Total Cholesterol > 200 mg/dL — review cardiovascular risk and lipid therapy.'),
    ('CHOL-CRITICAL-001',     'Critically High Cholesterol',       'lab_result',  'critical', 1, 48, 24, 1, 'Total Cholesterol > 300 mg/dL — significantly elevated cardiovascular risk.'),
    ('HYPO-K-001',            'Hypokalaemia',                      'lab_result',  'warning',  2, 24,  8, 1, 'Serum Potassium < 3.5 mEq/L — arrhythmia risk; potassium replacement indicated.'),
    ('SODIUM-HIGH-001',       'Hypernatraemia',                    'lab_result',  'warning',  2, 24,  8, 0, 'Serum Sodium > 150 mEq/L — evaluate for dehydration.'),
    ('SODIUM-LOW-001',        'Hyponatraemia',                     'lab_result',  'warning',  2, 24,  8, 0, 'Serum Sodium < 130 mEq/L — monitor for neurological symptoms.'),
    ('CREATININE-HIGH-001',   'Elevated Creatinine',               'lab_result',  'warning',  2, 24,  8, 0, 'Creatinine > 1.5 mg/dL — evaluate renal function.'),
    ('WBC-HIGH-001',          'Leukocytosis',                      'lab_result',  'warning',  2, 24,  8, 0, 'WBC > 11 × 10³/µL — evaluate for infection or inflammation.'),
    ('WBC-LOW-001',           'Leukopenia',                        'lab_result',  'warning',  2, 24,  8, 0, 'WBC < 4 × 10³/µL — evaluate for immunosuppression or haematological disorder.'),
    ('PLATELETS-LOW-001',     'Thrombocytopenia',                  'lab_result',  'critical', 1, 24, 12, 1, 'Platelets < 50 × 10³/µL — bleeding risk; review medications.')
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'vital','heart_rate','gt',150,'bpm','AND',1 FROM clinical_rules WHERE rule_code='TACHYCARDIA-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'vital','heart_rate','lt',40,'bpm','AND',1 FROM clinical_rules WHERE rule_code='BRADYCARDIA-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'vital','spo2','lt',90,'%','AND',1 FROM clinical_rules WHERE rule_code='HYPOXIA-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'vital','body_temperature','gt',38.5,'C','AND',1 FROM clinical_rules WHERE rule_code='HYPERTHERMIA-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'vital','body_temperature','lt',35,'C','AND',1 FROM clinical_rules WHERE rule_code='HYPOTHERMIA-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','glucose','lt',54,'mg/dL','AND',1 FROM clinical_rules WHERE rule_code='GLUCOSE-CRITICAL-LOW'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','glucose','lt',70,'mg/dL','AND',1 FROM clinical_rules WHERE rule_code='GLUCOSE-LOW-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','glucose','gt',200,'mg/dL','AND',1 FROM clinical_rules WHERE rule_code='GLUCOSE-HIGH-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','glucose','gt',500,'mg/dL','AND',1 FROM clinical_rules WHERE rule_code='GLUCOSE-CRITICAL-HIGH'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','hemoglobin','lt',7,'g/dL','AND',1 FROM clinical_rules WHERE rule_code='HGB-CRITICAL-LOW'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','hemoglobin','lt',12,'g/dL','AND',1 FROM clinical_rules WHERE rule_code='HGB-LOW-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','total_cholesterol','gt',200,'mg/dL','AND',1 FROM clinical_rules WHERE rule_code='CHOL-HIGH-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','total_cholesterol','gt',300,'mg/dL','AND',1 FROM clinical_rules WHERE rule_code='CHOL-CRITICAL-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','serum_potassium','lt',3.5,'mEq/L','AND',1 FROM clinical_rules WHERE rule_code='HYPO-K-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','serum_sodium','gt',150,'mEq/L','AND',1 FROM clinical_rules WHERE rule_code='SODIUM-HIGH-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','serum_sodium','lt',130,'mEq/L','AND',1 FROM clinical_rules WHERE rule_code='SODIUM-LOW-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','creatinine','gt',1.5,'mg/dL','AND',1 FROM clinical_rules WHERE rule_code='CREATININE-HIGH-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','wbc','gt',11,'x10³/µL','AND',1 FROM clinical_rules WHERE rule_code='WBC-HIGH-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','wbc','lt',4,'x10³/µL','AND',1 FROM clinical_rules WHERE rule_code='WBC-LOW-001'
ON CONFLICT DO NOTHING;
INSERT INTO rule_criteria (rule_id,data_domain,parameter_key,operator,threshold_value,threshold_unit,logic_join,sort_order)
SELECT id,'lab','platelets','lt',50,'x10³/µL','AND',1 FROM clinical_rules WHERE rule_code='PLATELETS-LOW-001'
ON CONFLICT DO NOTHING;
