-- PostgreSQL RBAC schema for the EHR database.
-- Run this while connected to the target database.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'nurse'
        CHECK (role IN ('admin', 'manager', 'doctor', 'nurse')),
    hospital VARCHAR(120) NOT NULL DEFAULT 'General Hospital',
    full_name VARCHAR(160),
    specialty VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_username UNIQUE (username),
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_hospital ON users (hospital);

CREATE TABLE IF NOT EXISTS user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    session_token VARCHAR(64) NOT NULL,
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    action VARCHAR(10) NOT NULL DEFAULT 'login'
        CHECK (action IN ('login', 'logout', 'expired')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_token ON user_sessions (session_token);

-- Replace the placeholder hashes with bcrypt hashes generated by PHP before
-- using these sample accounts. Production accounts should be provisioned
-- through the application rather than seeded with shared demo passwords.
INSERT INTO users (username, email, password_hash, role, full_name)
VALUES
    ('admin_user', 'admin@medalex.local', 'PASTE_REAL_BCRYPT_HASH_FOR_AdminPass123_HERE', 'admin', 'System Administrator'),
    ('dr_smith', 'dr.smith@medalex.local', 'PASTE_REAL_BCRYPT_HASH_FOR_DoctorPass123_HERE', 'doctor', 'Dr. Sarah Smith'),
    ('nurse_jones', 'nurse.jones@medalex.local', 'PASTE_REAL_BCRYPT_HASH_FOR_NursePass123_HERE', 'nurse', 'Nurse Emily Jones')
ON CONFLICT (username) DO NOTHING;
